
const AthleteEngine=(()=>{
const blocks=[
 {id:'warmup',title:'ÉCHAUFFEMENT',icon:'🔥',role:'Préparer sans fatiguer.'},
 {id:'main',title:'BLOC PRINCIPAL',icon:'🎯',role:'Travail central.'},
 {id:'support',title:'RENFORT UTILE',icon:'🛡️',role:'Renforcer et sécuriser.'},
 {id:'finish',title:'FINISHER / RETOUR',icon:'✅',role:'Finir ou récupérer.'}
];
const goals={
 musculation:{label:'Musculation',objective:'Force, masse utile et technique propre.',groups:['haut_du_corps','bas_du_corps','core'],badges:['Force','Charge','Repos','Tempo']},
 renfo:{label:'Renforcement',objective:'Tonus, posture, gainage et contrôle.',groups:['haut_du_corps','bas_du_corps','core','reeducation'],badges:['Posture','Gainage','Contrôle','Sécurité']},
 full:{label:'Full Body',objective:'Séance équilibrée haut, bas, core et cardio.',groups:['haut_du_corps','bas_du_corps','core','cardio'],badges:['Complet','Énergie','Cardio','Mental']},
 hiit:{label:'HIIT',objective:'Souffle, intervalles et intensité.',groups:['cardio','bas_du_corps','haut_du_corps','core'],badges:['Intensité','Chrono','Cardio','Calories']},
 circuit:{label:'Circuit Training',objective:'Ateliers, tours, rythme et alternance.',groups:['cardio','haut_du_corps','bas_du_corps','core'],badges:['Tours','Rythme','Renfo','Cardio']},
 boxe:{label:'Boxe',objective:'Technique, appuis, rounds, cardio et explosivité.',groups:['boxe','cardio','core','haut_du_corps','bas_du_corps'],badges:['Technique','Appuis','Rounds','Mental']},
 crossfit:{label:'CrossFit',objective:'WOD structuré : AMRAP, EMOM, For Time ou Skill.',groups:['cardio','bas_du_corps','haut_du_corps','core'],badges:['WOD','AMRAP','EMOM','Mental']},
 cross:{label:'Cross Training',objective:'Terrain, endurance, force utile et enchaînement.',groups:['cardio','bas_du_corps','haut_du_corps','core'],badges:['Terrain','Force','Endurance','Discipline']},
 hyrox:{label:'Hyrox',objective:'Stations, carries, transitions et endurance de force.',groups:['cardio','bas_du_corps','core','haut_du_corps'],badges:['Stations','Course','Carries','Transitions']},
 mobilite:{label:'Mobilité',objective:'Amplitude, respiration, récupération et souplesse.',groups:['mobilite','reeducation','core'],badges:['Souplesse','Respiration','Amplitude','Calme']},
 prevention:{label:'Prévention',objective:'Articulations, activation, contrôle et récupération.',groups:['reeducation','mobilite','core'],badges:['Sécurité','Activation','Contrôle','Récup']},
 explosivite:{label:'Explosivité',objective:'Puissance, vitesse, appuis et réactivité.',groups:['cardio','bas_du_corps','haut_du_corps','core'],badges:['Puissance','Vitesse','Appuis','Réactivité']}
};
const styles={
 musculation:[['force','Force','charges + repos'],['hypertrophie','Hypertrophie','volume'],['endurance_force','Endurance force','séries longues'],['push_pull','Push/Pull','haut'],['jambes','Jambes','bas']],
 renfo:[['posture','Posture','contrôle'],['core','Core','gainage'],['dos','Dos protecteur','prévention'],['senior','Adapté senior','sécurité']],
 full:[['equilibre','Équilibré','haut bas core'],['cardio_renfo','Cardio+renfo','alterné'],['force_full','Force complète','charges'],['terrain','Terrain','extérieur']],
 hiit:[['tabata','Tabata','20/10'],['interval','40/20','intervalles'],['brule','Brûle graisse','intense'],['boxing','Cardio boxing','fitness']],
 circuit:[['tours','Tours','3-5 tours'],['stations','Stations','ateliers'],['groupe','Groupe','plusieurs'],['cardio','Cardio mix','alternance']],
 boxe:[['pure','Boxe pure','rounds'],['renfo','Boxe+renfo','mix'],['cardio','Boxe cardio','30/30'],['boxing','Cardio boxing','public'],['appuis','Appuis défense','technique']],
 crossfit:[['wod','WOD','lisible'],['amrap','AMRAP','max tours'],['emom','EMOM','chaque minute'],['fortime','For Time','chrono'],['forcewod','Force+WOD','hybride'],['skill','Skill','technique']],
 cross:[['terrain','Terrain','course+renfo'],['endurance','Endurance','long effort'],['force','Force terrain','charges'],['team','Équipe','ateliers']],
 hyrox:[['stations','Stations','course+atelier'],['carries','Carries','portés'],['cardio','Cardio','rameur/course'],['simulation','Simulation','format course']],
 mobilite:[['bas','Bas du corps','hanches'],['haut','Haut du corps','épaules'],['colonne','Colonne','dos'],['relax','Relax','calme']],
 prevention:[['epaule','Épaules','coiffe'],['genou','Genoux','contrôle'],['dos','Dos','gainage'],['recup','Récupération','massage']],
 explosivite:[['vitesse','Vitesse','appuis'],['puissance','Puissance','sauts'],['reactivite','Réactivité','changements'],['athlete','Athlète','haut niveau']]
};
function profile(){try{return JSON.parse(localStorage.getItem('fafa_v67_profile')||'{}')}catch(e){return{}}}
function saveProfile(p){localStorage.setItem('fafa_v67_profile',JSON.stringify(p||{}))}
function history(){try{return JSON.parse(localStorage.getItem('fafa_v67_history')||'[]')}catch(e){return[]}}
function saveHistory(h){localStorage.setItem('fafa_v67_history',JSON.stringify((h||[]).slice(-80)))}
function weekPlan(){try{return JSON.parse(localStorage.getItem('fafa_v67_week')||'[]')}catch(e){return[]}}
function saveWeek(w){localStorage.setItem('fafa_v67_week',JSON.stringify(w||[]))}
function fmt(goal,style){if(style==='tabata')return{name:'TABATA',structure:'8 rounds',work:'20 sec',rest:'10 sec',reps:'max propre'};if(style==='emom')return{name:'EMOM',structure:'12 min',work:'début de minute',rest:'reste de minute',reps:'6-12 reps'};if(style==='amrap')return{name:'AMRAP',structure:'14 min',work:'enchaîner',rest:'si besoin',reps:'8-15 reps'};if(style==='fortime')return{name:'FOR TIME',structure:'cap 14 min',work:'finir la liste',rest:'court',reps:'10-20 reps'};if(goal==='boxe')return{name:'ROUNDS',structure:'3 à 5 rounds',work:'2-3 min',rest:'1 min',reps:'thème technique'};if(goal==='mobilite')return{name:'MOBILITÉ',structure:'2 à 3 tours',work:'45-60 sec',rest:'respiration',reps:'sans douleur'};if(goal==='prevention')return{name:'PRÉVENTION',structure:'2 à 3 séries',work:'10-15 reps',rest:'30-45 sec',reps:'contrôle'};if(goal==='explosivite')return{name:'PUISSANCE',structure:'4 à 6 séries',work:'3-6 reps',rest:'60-90 sec',reps:'explosif propre'};if(goal==='musculation')return{name:'SÉRIES',structure:'3 à 5 séries',work:'8-12 reps',rest:'60-90 sec',reps:'charge adaptée'};return{name:'CIRCUIT',structure:'3 à 5 tours',work:'10-15 reps ou 40 sec',rest:'60 sec/tour',reps:'affichées'}}
function split(d,goal){d=Number(d||30);if(goal==='mobilite'||goal==='prevention'){if(d<=20)return{warmup:3,main:10,support:5,finish:2};if(d<=30)return{warmup:4,main:15,support:8,finish:3};if(d<=45)return{warmup:6,main:22,support:12,finish:5};return{warmup:8,main:30,support:16,finish:6}}if(d<=20)return{warmup:4,main:9,support:5,finish:2};if(d<=30)return{warmup:5,main:14,support:7,finish:4};if(d<=45)return{warmup:7,main:22,support:10,finish:6};return{warmup:8,main:30,support:14,finish:8}}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function equipmentOk(e,eq){if(!eq||!eq.length)return true;let q=e.equipment||[];if(q.includes('poids du corps'))return true;return eq.some(x=>q.includes(x))}
function allowed(cfg,block){if(block==='warmup')return['mobilite','reeducation','cardio','boxe'];if(cfg.goal==='mobilite')return['mobilite','reeducation'];if(cfg.goal==='prevention')return['reeducation','mobilite','core'];if(cfg.goal==='boxe')return block==='main'?['boxe']:['boxe','cardio','core','reeducation'];if(block==='support')return['core','reeducation','haut_du_corps','bas_du_corps'];if(block==='finish')return cfg.goal==='mobilite'||cfg.goal==='prevention'?['mobilite','reeducation']:['cardio','boxe','core','bas_du_corps'];return goals[cfg.goal]?.groups||goals.full.groups}
function fatigueModifier(cfg){let p=profile(),mod=0,notes=[];if(Number(cfg.fatigue)>=4){mod-=1;notes.push('fatigue élevée : volume réduit')}if(Number(cfg.stress)>=4)notes.push('stress élevé : respiration/mobilité favorisée');if(Number(p.sleep||3)<=2){mod-=1;notes.push('sommeil faible : intensité modérée')}if(Number(p.recovery||3)<=2){mod-=1;notes.push('récupération faible : charge prudente')}return{mod,notes}}
function score(e,cfg,block,used,h){let p=profile(),s=0,g=allowed(cfg,block),obj=e.objectives||[];if(g.includes(e.group))s+=35;if(used.has(e.id))s-=120;if(h.some(x=>x.exerciseIds?.includes(e.id)))s-=7;if(!equipmentOk(e,cfg.equipment))s-=18;if(cfg.injury&&(e.contraindications||[]).includes(cfg.injury))s-=120;if(cfg.goal==='boxe'&&e.group==='boxe')s+=25;if(cfg.goal==='crossfit'&&obj.includes('crossfit'))s+=20;if(cfg.goal==='hyrox'&&obj.includes('hyrox'))s+=20;if(p.sport_main==='boxe'&&e.group==='boxe')s+=8;if(p.goal_long==='perte_gras'&&e.group==='cardio')s+=8;if(p.goal_long==='mobilite'&&e.group==='mobilite')s+=10;if(p.experience==='reprise'&&['mobilite','reeducation','core'].includes(e.group))s+=8;if(Number(p.age||cfg.age)>60&&['mobilite','reeducation','core'].includes(e.group))s+=10;if(Number(p.age||cfg.age)<15&&['mobilite','reeducation','core'].includes(e.group))s+=6;return s}
function count(cfg,block){let d=Number(cfg.duration||30),base=block==='main'?(d<=20?3:5):block==='warmup'?(d<=20?2:3):block==='support'?(d<=20?2:3):(cfg.goal==='mobilite'||cfg.goal==='prevention'?1:2);return Math.max(block==='main'?3:1,base+fatigueModifier(cfg).mod)}
function pick(exs,cfg,block,used,h){let n=count(cfg,block),list=shuffle(exs).map(e=>({e,s:score(e,cfg,block,used,h)})).filter(x=>x.s>-35).sort((a,b)=>b.s-a.s).map(x=>x.e);if(list.length<n)list=shuffle(exs).filter(e=>!used.has(e.id));let out=list.slice(0,n);out.forEach(e=>used.add(e.id));return out.map((e,i)=>adapt(e,cfg,block,i))}
function pres(e,cfg,block,i){let f=fmt(cfg.goal,cfg.style);if(block==='warmup')return'30-45 sec technique';if(block==='support')return'2-3 séries · contrôle';if(block==='finish')return cfg.goal==='boxe'?'30/30 sec':'30-45 sec';if(f.name==='AMRAP')return i%2?'12 reps':'10 reps';if(f.name==='EMOM')return'6-12 reps / minute';if(f.name==='TABATA')return'20 sec travail';if(f.name==='FOR TIME')return i%2?'15 reps':'10 reps';if(f.name==='ROUNDS')return'round 2-3 min';if(f.name==='SÉRIES')return'3-5 séries x 8-12 reps';if(f.name==='PUISSANCE')return'3-6 reps explosives';if(f.name==='MOBILITÉ')return'45-60 sec';if(f.name==='PRÉVENTION')return'10-15 reps contrôlées';return'10-15 reps ou 40 sec'}
function charge(e,cfg){let q=(e.equipment||[]).join(' '),p=profile(),lvl=cfg.level==='choisir'?(p.experience==='coach'?'avance':'intermediaire'):cfg.level;if(q.match(/barre|haltères|kettlebell|machine|poulie/)){if(lvl==='debutant')return'charge légère · technique';if(lvl==='intermediaire')return'RPE 7 · 2 reps en réserve';if(lvl==='avance')return'RPE 8 · technique stricte';return'RPE 8-9 · si maîtrisé'}return'poids du corps / contrôle'}
function adapt(e,cfg,block,i){let p=profile(),lvl=cfg.level==='choisir'?(p.experience==='reprise'?'debutant':'intermediaire'):cfg.level;return{...e,displayName:e.name,instruction:e.levels?.[lvl]||e.levels?.intermediaire||e.name,prescription:pres(e,cfg,block,i),charge:charge(e,cfg)}}
function info(cfg,block,items){let t=split(cfg.duration,cfg.goal),f=fmt(cfg.goal,cfg.style),mins=t[block];if(block==='warmup')return{minutes:mins,format:'Activation',structure:`${mins} min`,work:'30-45 sec/exercice',rest:'enchaîner propre',reps:'amplitude + respiration',coach:'préparer sans fatigue'};if(block==='support')return{minutes:mins,format:'Renfort utile',structure:`${mins} min`,work:`${items.length} exercices`,rest:'30-45 sec',reps:'contrôle + posture',coach:'corriger les points faibles'};if(block==='finish')return{minutes:mins,format:cfg.goal==='mobilite'||cfg.goal==='prevention'?'Retour au calme':'Finisher',structure:`${mins} min`,work:'court et propre',rest:'adapté',reps:'finir sans casser la technique',coach:'respecter la forme'};return{minutes:mins,format:f.name,structure:f.name==='AMRAP'?`AMRAP ${mins} min`:f.name==='EMOM'?`EMOM ${mins} min`:f.name==='FOR TIME'?`For Time ${mins} min`:f.structure,work:f.work,rest:f.rest,reps:f.reps,coach:'rythme constant, qualité avant ego'}}
function adaptation(cfg){let p=profile(),a=fatigueModifier(cfg).notes;if(p.name)a.unshift(`athlète : ${p.name}`);if(p.goal_long)a.push(`objectif long terme : ${p.goal_long}`);if(p.sessions_week)a.push(`${p.sessions_week} séance(s)/semaine`);if(cfg.injury)a.push(`zone à protéger : ${cfg.injury}`);return a.length?a.join(' · '):'profil standard : progression équilibrée'}
function generate(raw,exs){let p=profile(),cfg={goal:'full',style:'equilibre',level:'intermediaire',duration:30,equipment:['poids du corps'],age:p.age||'',people:1,fatigue:3,stress:3,injury:'',place:'',...raw};let used=new Set(),h=history(),g=goals[cfg.goal]||goals.full,s={id:Date.now(),date:new Date().toISOString(),title:g.label,objective:g.objective,adaptation:adaptation(cfg),theme:g,meta:{...cfg,equipment:(cfg.equipment||[]).join(', ')},blocks:{},infos:{}};blocks.forEach(b=>{s.blocks[b.id]=pick(exs,cfg,b.id,used,h);s.infos[b.id]=info(cfg,b.id,s.blocks[b.id])});return s}
function saveSession(s){let h=history();h.unshift({id:s.id,date:s.date,title:s.title,goal:s.meta.goal,style:s.meta.style,duration:s.meta.duration,exerciseIds:Object.values(s.blocks).flat().map(e=>e.id)});saveHistory(h);return h}
function stats(){let h=history(),by={};h.forEach(x=>by[x.goal]=(by[x.goal]||0)+1);return{total:h.length,last:h[0]||null,byGoal:by}}
function recommendations(){let p=profile(),st=stats(),rec=[];if(!p.name)rec.push('Complète ton profil athlète pour une adaptation plus précise.');if(st.total===0)rec.push('Génère puis sauvegarde ta première séance.');if(Number(p.sessions_week||0)>=4)rec.push('Ajoute une séance mobilité/récupération dans la semaine.');if(Number(p.sleep||3)<=2)rec.push('Sommeil faible : privilégie mobilité ou technique.');if(!rec.length)rec.push('Continue : alterne intensité, technique et récupération.');return rec}
function generateWeek(exs){let p=profile(),n=Math.max(1,Math.min(6,Number(p.sessions_week||3))),order=['full','musculation','mobilite','boxe','hiit','prevention'];if(p.sport_main==='boxe')order=['boxe','renfo','mobilite','boxe','hiit','prevention'];if(p.goal_long==='perte_gras')order=['hiit','full','mobilite','circuit','boxe','prevention'];if(p.goal_long==='force')order=['musculation','mobilite','renfo','musculation','full','prevention'];let week=[];for(let i=0;i<n;i++){let goal=order[i%order.length],style=(styles[goal]||styles.full)[0][0];week.push(generate({goal,style,duration:i%3===0?30:45,level:p.experience==='reprise'?'debutant':'intermediaire',equipment:['poids du corps']},exs))}saveWeek(week.map(w=>({id:w.id,title:w.title,goal:w.meta.goal,duration:w.meta.duration,style:w.meta.style})));return week}
return{blocks,goals,styles,generate,saveSession,profile,saveProfile,history,saveHistory,stats,recommendations,generateWeek,weekPlan,saveWeek};
})();
