
const CoachOS=(()=>{
const GOALS={
 musculation:["Musculation","Force, masse, contrôle.",["haut_du_corps","bas_du_corps","core"],["Force","Charge","Tempo","Repos"]],
 force:["Force","Charges lourdes, technique stricte.",["haut_du_corps","bas_du_corps","core"],["Lourd","RPE","Technique","Repos"]],
 hypertrophie:["Prise de masse","Volume musculaire et tempo.",["haut_du_corps","bas_du_corps","core"],["Volume","8-12","Pump","Tempo"]],
 perte_gras:["Perte de poids","Dépense, régularité, renfo.",["cardio","bas_du_corps","haut_du_corps","core"],["Cardio","Circuit","Calories","Rythme"]],
 full:["Full Body","Tout le corps, séance équilibrée.",["haut_du_corps","bas_du_corps","core","cardio"],["Complet","Core","Énergie","Mental"]],
 hiit:["HIIT","Intervalles courts, intensité.",["cardio","bas_du_corps","haut_du_corps","core"],["Chrono","Intensité","Cardio","Impact"]],
 circuit:["Circuit Training","Ateliers, tours, groupe.",["cardio","haut_du_corps","bas_du_corps","core"],["Tours","Ateliers","Rythme","Groupe"]],
 boxe:["Boxe","Rounds, appuis, garde, cardio.",["boxe","cardio","core","haut_du_corps","bas_du_corps"],["Rounds","Appuis","Garde","Mental"]],
 cardio_boxing:["Cardio Boxing","Boxe fitness, rythme et dépense.",["boxe","cardio","core"],["Boxing","Rythme","Fun","Cardio"]],
 crossfit:["CrossFit","WOD, AMRAP, EMOM, For Time.",["cardio","bas_du_corps","haut_du_corps","core"],["WOD","AMRAP","EMOM","For Time"]],
 hyrox:["Hyrox","Stations, ergos, course, portés.",["cardio","bas_du_corps","core","haut_du_corps"],["Stations","Carries","Erg","Endurance"]],
 explosivite:["Explosivité","Vitesse, puissance, appuis.",["cardio","bas_du_corps","haut_du_corps","core"],["Puissance","Vitesse","Appuis","Repos"]],
 mobilite:["Mobilité","Amplitude, respiration, souplesse.",["mobilite","reeducation","core"],["Souplesse","Amplitude","Respiration","Calme"]],
 prevention:["Prévention","Protéger, stabiliser, corriger.",["reeducation","mobilite","core"],["Sécurité","Contrôle","Activation","Récup"]],
 recovery:["Recovery","Récupérer, respirer, relâcher.",["mobilite","reeducation"],["Calme","Relâchement","Respiration","Douleur 0"]],
 senior:["Sport santé","Bouger en sécurité.",["reeducation","mobilite","core","bas_du_corps"],["Santé","Stable","Progressif","Sécurité"]],
 outdoor:["Outdoor","Terrain, simple, efficace.",["cardio","bas_du_corps","core","haut_du_corps"],["Terrain","Course","Renfo","Simple"]]
};
const STYLE={
 force:[["force_pure","Force pure"],["force_tech","Force technique"],["lower_strength","Jambes"],["upper_strength","Haut"]],
 hypertrophie:[["volume","Volume"],["tempo","Tempo"],["pump","Pump"],["full_muscle","Full muscle"]],
 musculation:[["global","Global"],["haut","Haut"],["bas","Bas"],["split","Split"]],
 perte_gras:[["circuit","Circuit"],["hiit_low","HIIT adapté"],["cardio_renfo","Cardio + renfo"],["boxing_burn","Boxing burn"]],
 full:[["equilibre","Équilibré"],["cardio_renfo","Cardio + renfo"],["force_full","Force complète"],["terrain","Terrain"]],
 hiit:[["tabata","Tabata"],["interval","40/20"],["low_impact","Sans impact"],["boxing","Boxing"]],
 circuit:[["tours","Tours"],["stations","Stations"],["groupe","Groupe"],["cardio","Cardio mix"]],
 boxe:[["pure","Boxe pure"],["sac","Sac"],["renfo","Boxe + renfo"],["appuis","Appuis"],["pro","Boxeur pro"]],
 cardio_boxing:[["fitness","Fitness"],["30_30","30/30"],["coordination","Coordination"],["burn","Burn"]],
 crossfit:[["wod","WOD"],["amrap","AMRAP"],["emom","EMOM"],["fortime","For Time"],["skill","Skill"]],
 hyrox:[["stations","Stations"],["carries","Carries"],["erg","Erg"],["simulation","Simulation"]],
 explosivite:[["vitesse","Vitesse"],["puissance","Puissance"],["reactivite","Réactivité"],["athlete","Athlète"]],
 mobilite:[["bas","Bas du corps"],["haut","Haut du corps"],["colonne","Colonne"],["respiration","Respiration"]],
 prevention:[["epaule","Épaules"],["genou","Genoux"],["dos","Dos"],["cheville","Chevilles"]],
 recovery:[["relax","Relax"],["respiration","Respiration"],["deverrouillage","Déverrouillage"],["douce","Douce"]],
 senior:[["mobilite","Mobilité"],["renfo_doux","Renfo doux"],["equilibre","Équilibre"],["souffle","Souffle"]],
 outdoor:[["terrain","Terrain"],["parc","Parc"],["groupe","Groupe"],["endurance","Endurance"]]
};
const BLOCKS=[["warmup","Échauffement","🔥"],["skill","Technique","🎯"],["main","Bloc principal","⚡"],["support","Renfort utile","🛡️"],["finish","Retour / Finisher","🌙"]];
function profile(){try{return JSON.parse(localStorage.getItem("fafa75_profile")||localStorage.getItem("fafa74_profile")||"{}")}catch(e){return{}}}
function saveProfile(p){localStorage.setItem("fafa75_profile",JSON.stringify(p||{}))}
function history(){try{return JSON.parse(localStorage.getItem("fafa75_history")||"[]")}catch(e){return[]}}
function saveSession(s){let h=history();h.unshift({id:s.id,date:s.date,title:s.title,goal:s.meta.goal,duration:s.meta.duration,score:s.score,exerciseIds:s.exerciseIds||[]});localStorage.setItem("fafa75_history",JSON.stringify(h.slice(0,120)))}
function bmi(weight,height){let w=+weight,h=+height/100;if(!w||!h)return{value:null,label:"IMC non renseigné",note:"Renseigne taille et poids."};let v=Math.round((w/(h*h))*10)/10,label="IMC normal",note="À nuancer selon masse musculaire.";if(v<18.5){label="IMC bas";note="Priorité force, masse utile, récupération."}else if(v<25){label="IMC normal";note="Bonne base, vérifier composition corporelle."}else if(v<30){label="Surpoids";note="À nuancer si sportif/musclé. Régularité + renfo."}else{label="IMC élevé";note="Progressivité, faible impact, avis médical si besoin."}return{value:v,label,note}}
function rpe(level,fatigue,goal){let v={debutant:6,intermediaire:7,avance:8,expert:8.5,auto:7}[level]||7;if(["force","hiit","crossfit","hyrox","boxe"].includes(goal))v+=.5;if(+fatigue>=4)v-=1;return Math.max(5,Math.min(9,Math.round(v*10)/10))}
function prescription(goal,style,level,fatigue){let R=rpe(level,fatigue,goal);if(goal==="force")return{sets:"4-5",reps:"3-6",rest:"2-3 min",load:`lourd · RPE ${R}`,tempo:"contrôle"};if(goal==="hypertrophie"||goal==="musculation")return{sets:"3-4",reps:"8-12",rest:"60-90 sec",load:`modéré · RPE ${R}`,tempo:"2-0-2"};if(goal==="perte_gras"||goal==="hiit")return{sets:"3-5 tours",reps:style==="tabata"?"20/10":"30-45 sec",rest:"30-60 sec",load:`léger/modéré · RPE ${R}`,tempo:"rythme propre"};if(goal==="boxe")return{sets:(level==="expert"||level==="avance")?"5 rounds":"3-4 rounds",reps:(level==="expert"||level==="avance")?"3 min":"2 min",rest:"1 min",load:"sac / poids du corps",tempo:"garde + appuis"};if(goal==="crossfit")return{sets:style==="emom"?"EMOM 12":"AMRAP 12-16",reps:"8-15 reps",rest:"selon format",load:`technique · RPE ${R}`,tempo:"constant"};if(goal==="hyrox")return{sets:"4 stations",reps:"500m / 40-60 sec",rest:"60 sec",load:`modéré · RPE ${R}`,tempo:"endurance force"};if(goal==="mobilite"||goal==="recovery")return{sets:"2-3 tours",reps:"45-60 sec",rest:"respiration",load:"sans charge",tempo:"lent"};if(goal==="prevention"||goal==="senior")return{sets:"2-3",reps:"8-15 reps",rest:"45-60 sec",load:"léger",tempo:"contrôle"};return{sets:"3-4 tours",reps:"10-15 reps",rest:"45-60 sec",load:`modéré · RPE ${R}`,tempo:"propre"}}
function calories(duration,weight,goal){let w=+weight||75,d=+duration||30,met={mobilite:2.5,recovery:2.2,prevention:3,senior:3.2,force:5,musculation:5.5,hypertrophie:5.5,boxe:8,cardio_boxing:8.5,hiit:9,crossfit:9,hyrox:8.5,perte_gras:7,circuit:7,full:6,outdoor:6,explosivite:6.5}[goal]||6;return Math.round((met*3.5*w/200)*d)}
function allowed(goal,block){if(block==="warmup")return["mobilite","reeducation","cardio","boxe"];if(block==="skill"){if(goal==="boxe"||goal==="cardio_boxing")return["boxe"];if(goal==="mobilite"||goal==="recovery")return["mobilite"];if(goal==="prevention"||goal==="senior")return["reeducation","mobilite"];return["core","mobilite","haut_du_corps","bas_du_corps"]}if(goal==="mobilite"||goal==="recovery")return["mobilite","reeducation"];if(goal==="prevention"||goal==="senior")return["reeducation","mobilite","core","bas_du_corps"];if(goal==="boxe"||goal==="cardio_boxing")return block==="main"?["boxe","cardio"]:["boxe","cardio","core","reeducation"];if(block==="support")return["core","reeducation","mobilite","haut_du_corps","bas_du_corps"];if(block==="finish")return goal==="force"||goal==="hypertrophie"?["core","mobilite"]:["cardio","boxe","core","mobilite"];return GOALS[goal]?.[2]||GOALS.full[2]}
function eqOk(e,eq){if(!eq||!eq.length)return true;let q=e.equipment||[];return q.includes("poids du corps")||eq.some(x=>q.includes(x))}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function recent(){return new Set(history().slice(0,8).flatMap(x=>x.exerciseIds||[]))}
function scoreExercise(e,cfg,block,used,rec){let s=0,g=allowed(cfg.goal,block),obj=e.objectives||[];if(g.includes(e.group))s+=50;if(obj.includes(cfg.goal))s+=25;if(cfg.style&&obj.includes(cfg.style))s+=10;if(used.has(e.id))s-=200;if(rec.has(e.id))s-=35;if(!eqOk(e,cfg.equipment))s-=25;if(cfg.injury&&(e.contraindications||[]).includes(cfg.injury))s-=150;if(+cfg.age>60&&["reeducation","mobilite","core"].includes(e.group))s+=14;if(+cfg.age<15&&["reeducation","mobilite","core","boxe"].includes(e.group))s+=9;if(+cfg.fatigue>=4&&e.group==="cardio")s-=12;if(+cfg.stress>=4&&["mobilite","reeducation"].includes(e.group))s+=14;return s}
function blockCount(block,d,g,fatigue){d=+d||30;let c=block==="main"?(d<=20?3:4):block==="warmup"?(d<=20?2:3):block==="skill"?(d<=20?1:2):block==="support"?(d<=20?2:3):2;if(g==="mobilite"||g==="recovery"){if(block==="main")c=4;if(block==="skill")c=1}if(+fatigue>=4&&c>2)c--;return c}
function adapt(e,cfg,block,p){let lvl=cfg.level==="auto"?"intermediaire":cfg.level,rx=block==="warmup"?"30-45 sec":block==="skill"?"2 séries techniques":block==="main"?`${p.sets} · ${p.reps}`:block==="support"?"2-3 séries contrôle":(cfg.goal==="mobilite"||cfg.goal==="recovery"?"45-60 sec":"30-45 sec");return{...e,displayName:e.name,instruction:e.levels?.[lvl]||e.levels?.intermediaire||e.name,prescription:rx,load:p.load,rest:p.rest,tempo:p.tempo}}
function pick(exs,cfg,block,used,p,rec){let n=blockCount(block,cfg.duration,cfg.goal,cfg.fatigue);let list=shuffle(exs).map(e=>({e,s:scoreExercise(e,cfg,block,used,rec)})).filter(x=>x.s>-60).sort((a,b)=>b.s-a.s).map(x=>x.e);if(list.length<n)list=shuffle(exs).filter(e=>!used.has(e.id));let out=list.slice(0,n);out.forEach(e=>used.add(e.id));return out.map(e=>adapt(e,cfg,block,p))}
function info(cfg,block,p){let d=+cfg.duration||30,map={warmup:.15,skill:.12,main:.43,support:.20,finish:.10},mins=Math.max(2,Math.round(d*(map[block]||.2)));if(block==="main")return{format:p.sets,structure:`${mins} min`,work:p.reps,rest:p.rest,load:p.load,tempo:p.tempo};if(block==="warmup")return{format:"Activation",structure:`${mins} min`,work:"30-45 sec",rest:"court",load:"progressif",tempo:"propre"};if(block==="skill")return{format:"Technique",structure:`${mins} min`,work:"2 passages",rest:"qualité",load:"léger",tempo:"apprentissage"};if(block==="support")return{format:"Renfort",structure:`${mins} min`,work:"contrôle",rest:"45 sec",load:"léger/modéré",tempo:"stable"};return{format:"Final",structure:`${mins} min`,work:"court",rest:"adapté",load:"adapté",tempo:"fin propre"}}
function coachNotes(cfg,b){let arr=[];if(b.value)arr.push(`IMC ${b.value} : ${b.label}`);if(+cfg.fatigue>=4)arr.push("volume réduit");if(+cfg.stress>=4)arr.push("respiration renforcée");if(cfg.injury)arr.push(`protéger ${cfg.injury}`);return arr.join(" · ")||"séance équilibrée"}
function eliteScore(cfg,b){let s=82;if(!b.value)s-=8;if(+cfg.fatigue>=4)s-=5;if(+cfg.stress>=4)s-=4;if(cfg.injury)s-=3;if((cfg.equipment||[]).length>2)s+=5;return Math.max(55,Math.min(98,s))}
function generate(cfg,exs){cfg={goal:"full",style:"equilibre",level:"auto",duration:30,equipment:["poids du corps"],age:"",height:"",weight:"",sex:"",fatigue:3,stress:3,recovery:3,injury:"",place:"choisir",people:1,...cfg};let b=bmi(cfg.weight,cfg.height),p=prescription(cfg.goal,cfg.style,cfg.level,cfg.fatigue),g=GOALS[cfg.goal]||GOALS.full,used=new Set(),rec=recent();let s={id:Date.now(),date:new Date().toISOString(),title:g[0],objective:g[1],badges:g[3],bmi:b,prescription:p,calories:calories(cfg.duration,cfg.weight,cfg.goal),coachNotes:coachNotes(cfg,b),score:eliteScore(cfg,b),meta:cfg,blocks:{},infos:{}};BLOCKS.forEach(bl=>{s.blocks[bl[0]]=pick(exs,cfg,bl[0],used,p,rec);s.infos[bl[0]]=info(cfg,bl[0],p)});s.exerciseIds=Object.values(s.blocks).flat().map(e=>e.id);return s}
return{GOALS,STYLE,BLOCKS,profile,saveProfile,history,saveSession,bmi,prescription,generate};
})();
