
const STORE='fafatraining_v33_rebuild_propre';
const ASSETS=window.FAFA_ASSETS||{};
let exercises=[],programs=[],visuals={},levels={},session=[];
let state={
 tab:'home', profileCreated:false, sessionGenerated:false,
 program:'full_body', duration:'standard', exIndex:0,setDone:0,timeLeft:0,running:false,history:[],
 profile:{name:'',age:'',height:'',weight:'',level:'debutant',goal:'remise_forme',place:'',fatigue:'',sleep:'',stress:'',injuries:[],equipment:[]}
};
function $(s){return document.querySelector(s)}
function safe(x){return String(x??'').replace(/[<>&]/g,s=>({'<':'&lt;','>':'&gt;','&':'&amp;'}[s]))}
async function boot(){[exercises,programs,visuals,levels]=await Promise.all([fetch('data/exercises.json').then(r=>r.json()),fetch('data/programs.json').then(r=>r.json()),fetch('data/visual_map.json').then(r=>r.json()),fetch('data/level_rules.json').then(r=>r.json())]);let old=localStorage.getItem(STORE);if(old)state={...state,...JSON.parse(old)};if(state.sessionGenerated)buildSession();render()}
function save(){localStorage.setItem(STORE,JSON.stringify(state))}
function currentProgram(){return programs.find(p=>p.id===state.program)||programs[0]}
function level(){return levels[state.profile.level]||levels.debutant}
function bmi(){let h=Number(state.profile.height)/100,w=Number(state.profile.weight);if(!h||!w)return null;return +(w/(h*h)).toFixed(1)}
function bmiText(){let b=bmi();if(!b)return 'Non renseigné';if(b<18.5)return b+' · bas';if(b<25)return b+' · normal';if(b<30)return b+' · élevé';return b+' · très élevé'}
function readiness(){if(!state.profileCreated)return null;let p=state.profile;let fatigue=Number(p.fatigue||3),stress=Number(p.stress||2),sleep=Number(p.sleep||7);let s=100-fatigue*12-stress*7+Math.max(0,sleep-6)*4;if(p.injuries.length)s-=8;return Math.max(30,Math.min(100,Math.round(s)))}
function sessionCount(){let c=level().counts[state.duration]||level().counts.standard;let r=readiness();if(r&&r<60)c=Math.max(4,c-2);return c}
function isOk(e){let p=state.profile,pr=currentProgram(),score=level().score||1;return pr.categories.includes(e.category)&&e.levelMin<=score&&e.equipment.some(eq=>p.equipment.includes(eq))&&!(e.avoidIf||[]).some(i=>p.injuries.includes(i))}
function buildSession(){let pool=exercises.filter(isOk);if(pool.length<4)pool=exercises.filter(e=>currentProgram().categories.includes(e.category)&&e.levelMin<=level().score);let warm=pool.filter(e=>['mobilite','core','cardio_crossfit'].includes(e.category)).slice(0,2),main=pool.filter(e=>!['mobilite'].includes(e.category)).slice(0,Math.max(2,sessionCount()-3)),fin=pool.filter(e=>['cardio_crossfit','core','boxe'].includes(e.category)).slice(0,2);session=[...warm,...main,...fin].filter((v,i,a)=>a.findIndex(x=>x.key===v.key)===i).slice(0,sessionCount());state.exIndex=0;state.setDone=0;state.sessionGenerated=true}
function setTab(t){state.tab=t;save();render()}
function layout(content,side=true){return `<div class="app"><header class="top"><div class="topin"><div class="brand"><img src="${ASSETS.logo}"><div><h1>FAFATRAINING COACHING</h1><p>Force ton corps · élève ton mental</p></div></div><nav class="tabs">${['home:Accueil','coach:Coach','session:Séance','library:Exercices','tracking:Suivi'].map(v=>{let[id,l]=v.split(':');return`<button class="tab ${state.tab===id?'active':''}" onclick="setTab('${id}')">${l}</button>`}).join('')}</nav></div></header><main class="main">${side?`<div class="layout"><section>${content}</section>${sidePanel()}</div>`:content}</main><nav class="bottom">${['home:🏠:Accueil','coach:👤:Coach','session:▶:Séance','library:🔎:Exos','tracking:📊:Suivi'].map(v=>{let[id,ic,l]=v.split(':');return`<button onclick="setTab('${id}')">${ic}<small>${l}</small></button>`}).join('')}</nav></div>`}
function sidePanel(){if(!state.profileCreated)return `<aside class="side"><h2>Bienvenue</h2><p class="muted">Crée d’abord ton profil pour générer une séance adaptée.</p><button class="btn" onclick="setTab('coach')">Créer profil</button></aside>`;let p=state.profile,pr=currentProgram(),r=readiness();return`<aside class="side"><button class="btn secondary" onclick="setTab('home')">← Retour accueil</button><h2>${safe(p.name||'Profil')}</h2><p class="muted">${safe(level().label)} · ${safe(goalLabel(p.goal))}</p><span class="pill p-green">${safe(p.place||'lieu non défini')}</span><span class="pill p-lime">forme ${r}%</span><div class="progress"><span style="width:${r}%"></span></div><p class="muted">IMC : ${bmiText()}</p><hr style="border-color:var(--line)"><h3>Séance</h3>${state.sessionGenerated?`<p><b>${safe(pr.name)}</b><br><span class="muted">${safe(pr.duration)}</span></p><button class="btn" onclick="setTab('session')">Lancer</button><button class="btn secondary" onclick="exportPDF()">Exporter PDF</button>`:`<p class="muted">Aucune séance générée.</p><button class="btn" onclick="setTab('coach')">Générer</button>`}</aside>`}
function goalLabel(g){return{remise_forme:'Remise en forme',perte_poids:'Perte de poids',prise_masse:'Prise de masse',performance:'Performance',bien_etre:'Bien-être'}[g]||g}
function home(){if(!state.profileCreated)return layout(`<div class="hero"><div class="empty heroText"><div class="tag">NOUVEAU DÉPART</div><h2>Bienvenue.</h2><p>Avant les pourcentages, les statistiques ou les séances, on crée ton profil. Comme une vraie application : rien n’est simulé.</p><div class="actions"><button class="btn" onclick="setTab('coach')">Créer mon profil</button><button class="btn secondary" onclick="setTab('library')">Voir la bibliothèque</button></div></div><div class="card logoHero"><img src="${ASSETS.logo}"></div></div><div class="card"><h2>À quoi sert l’app ?</h2><p>Créer une séance adaptée au niveau, au matériel, aux blessures, au temps disponible et à l’objectif. Ensuite seulement, l’app suit la progression.</p></div>`);let pr=currentProgram();return layout(`<div class="hero"><div class="card heroText"><div class="tag">PROFIL PRÊT</div><h2>Bonjour ${safe(state.profile.name||'coach')}.</h2><p>Ton profil est créé. Tu peux générer ta séance ou modifier les réglages.</p><div class="actions"><button class="btn" onclick="generateAndGo()">Générer ma séance</button><button class="btn secondary" onclick="setTab('coach')">Modifier profil</button></div></div><div class="card logoHero"><img src="${ASSETS.logo}"></div></div>${state.sessionGenerated?`<div class="today"><span class="tag">SÉANCE PRÊTE</span><h2>${safe(pr.name)}</h2><p>${safe(pr.description)} · ${safe(pr.duration)}</p></div><div class="stats"><div class="stat"><b>${session.length}</b>Exos</div><div class="stat"><b>${readiness()}%</b>Forme</div><div class="stat"><b>${exercises.length}</b>Exercices</div><div class="stat"><b>${state.history.length}</b>Faites</div></div>`:`<div class="empty"><h2>Aucune séance générée</h2><p>Rien n’est affiché comme fait tant que tu n’as pas lancé une vraie séance.</p></div>`}`)}
function generateAndGo(){buildSession();state.sessionGenerated=true;save();setTab('session')}
function visual(e){let v=visuals[e.key]||{};return`<img src="${v.image}" onerror="this.src='${v.fallback}'"><span class="vlabel pill p-green">${safe(e.key)}.jpg</span>`}
function sessionView(){if(!state.profileCreated)return layout(`<div class="empty"><h2>Crée ton profil d’abord</h2><p>La séance ne démarre pas tant que le profil n’est pas rempli.</p><button class="btn" onclick="setTab('coach')">Créer profil</button></div>`,false);if(!state.sessionGenerated||!session.length)return layout(`<div class="empty"><h2>Aucune séance générée</h2><p>Choisis tes infos dans Coach puis clique sur “Générer séance”.</p><button class="btn" onclick="setTab('coach')">Aller dans Coach</button></div>`,false);let e=session[state.exIndex]||session[0],l=level(),reps=['cardio_crossfit','mobilite','boxe'].includes(e.category)?l.time:l.reps+' répétitions';return layout(`<div class="sessionLayout"><section class="exercise"><div class="visual">${visual(e)}</div><div class="exerciseInfo"><span class="pill p-green">${state.exIndex+1}/${session.length}</span><span class="pill p-blue">${safe(l.difficulty)}</span><span class="pill p-orange">${safe(e.category)}</span><h2>${safe(e.name)}</h2><p class="muted">${safe(e.muscles)}</p><div class="numbers"><div class="num"><b>${l.sets}</b>Séries</div><div class="num"><b>${safe(reps)}</b>À faire</div><div class="num"><b>${l.rest}s</b>Repos</div><div class="num"><b>${state.setDone}/${l.sets}</b>Fait</div></div><div class="coachBox"><b>Explication novice</b><p>${safe(e.novice)}</p><b>Consigne simple</b><p>${safe(e.simple)}</p><b>À éviter</b><p>${safe(e.mistake)}</p><b>Variantes</b><p>${safe(e.variants.join(' · '))}</p></div><div class="actions"><button class="btn" onclick="startRest(${l.rest})">⏱ Démarrer repos</button><button class="btn secondary" onclick="doneSet()">✓ Série faite</button><button class="btn secondary" onclick="nextExercise()">Suivant →</button></div></div></section><aside class="timerPanel"><h2>Chrono</h2><div class="timer" id="timer">${state.timeLeft||l.rest}s</div><p class="muted">Repos automatique.</p><div class="actions"><button class="btn secondary" onclick="pauseTimer()">Pause</button><button class="btn red" onclick="resetTimer()">Reset</button></div></aside></div>`,false)}
function startRest(sec){state.timeLeft=sec;state.running=true;save();clearInterval(window._timer);window._timer=setInterval(()=>{if(!state.running)return;state.timeLeft--;let t=$('#timer');if(t)t.textContent=state.timeLeft+'s';if(state.timeLeft<=0){state.running=false;clearInterval(window._timer);save()}},1000);render()}function pauseTimer(){state.running=false;save()}function resetTimer(){state.timeLeft=level().rest;state.running=false;save();render()}function doneSet(){state.setDone++;if(state.setDone>=level().sets)nextExercise();else{state.timeLeft=level().rest;save();render()}}function nextExercise(){state.exIndex++;state.setDone=0;state.running=false;if(state.exIndex>=session.length){state.history.push({date:new Date().toLocaleDateString('fr-FR'),program:currentProgram().name,count:session.length,form:readiness()});state.exIndex=0;state.sessionGenerated=false;session=[];alert('Séance terminée ✅')}save();render()}
function library(){return layout(`<div class="card"><h2>Bibliothèque pédagogique</h2><p class="muted">Chaque exercice contient une explication novice, les erreurs à éviter et les variantes.</p><div class="form"><label>Recherche<input id="q" oninput="filterLib()" placeholder="squat, boxe, haltères..."></label><label>Catégorie<select id="cat" onchange="filterLib()"><option value="">Toutes</option>${[...new Set(exercises.map(e=>e.category))].map(c=>`<option>${c}</option>`).join('')}</select></label><label>Matériel<select id="eq" onchange="filterLib()"><option value="">Tous</option>${[...new Set(exercises.flatMap(e=>e.equipment))].sort().map(c=>`<option>${c}</option>`).join('')}</select></label></div></div><div class="grid grid2">${exercises.map(e=>`<div class="libItem" data-t="${safe((e.name+' '+e.category+' '+e.equipment.join(' ')).toLowerCase())}"><div class="thumb"><img src="${visuals[e.key]?.image}" onerror="this.remove()">Photo</div><div><b>${safe(e.name)}</b><p class="muted">${safe(e.muscles)}</p><span class="pill p-green">${safe(e.category)}</span><div class="details"><b>Novice :</b> ${safe(e.novice)}<br><b>Erreur :</b> ${safe(e.mistake)}</div></div></div>`).join('')}</div>`)}
function filterLib(){let q=($('#q')?.value||'').toLowerCase(),cat=$('#cat')?.value||'',eq=$('#eq')?.value||'';document.querySelectorAll('.libItem').forEach(it=>{let txt=it.dataset.t;it.style.display=(txt.includes(q)&&(!cat||txt.includes(cat))&&(!eq||txt.includes(eq)))?'grid':'none'})}
function tracking(){if(!state.history.length)return layout(`<div class="empty"><h2>Aucune donnée pour le moment</h2><p>Le suivi reste vide tant qu’aucune séance n’a été terminée.</p><button class="btn" onclick="setTab('session')">Commencer une séance</button></div>`);return layout(`<div class="card"><h2>Suivi utile</h2><div class="stats"><div class="stat"><b>${state.history.length}</b>Séances</div><div class="stat"><b>${readiness()}%</b>Forme</div><div class="stat"><b>${safe(level().label)}</b>Niveau</div><div class="stat"><b>${bmiText()}</b>IMC</div></div></div><div class="card"><h2>Historique</h2>${state.history.slice().reverse().map(h=>`<p>✅ ${h.date} · ${safe(h.program)} · ${h.count} exos · forme ${h.form}%</p>`).join('')}</div><div class="card"><h2>Carré client</h2><div class="poster">${posterHTML()}</div><br><button class="btn" onclick="printPoster()">Exporter carré Insta</button></div>`)}
function posterHTML(){let blocks=[['ENTRÉE','Activation',...session.slice(0,3)],['PLAT','Bloc principal',...session.slice(3,7)],['FINISHER','Explosif',...session.slice(7,10)]];return`<h2>MENU SÉANCE</h2><p>FAFATRAINING · ${safe(currentProgram().name)}</p>${blocks.map(b=>`<div class="posterRow"><div class="posterCell"><b>${b[0]}</b><br>${b[1]}</div>${b.slice(2).map(e=>`<div class="posterCell">${e?'<b>'+safe(e.name)+'</b><br>'+safe(e.muscles):'-'}</div>`).join('')}</div>`).join('')}`}function printPoster(){let w=window.open('','_blank');w.document.write(`<html><head><link rel="stylesheet" href="style.css"><style>body{background:#050805;padding:20px}.poster{width:1080px;height:1080px}</style></head><body><div class="poster">${posterHTML()}</div><script>setTimeout(()=>print(),500)<\\/script></body></html>`);w.document.close()}
function coach(){let p=state.profile;return layout(`<div class="card"><h2>Coach / Profil</h2><p class="muted">Ici on crée le vrai profil. Rien n’est pré-coché. Rien n’est simulé.</p><div class="form"><label>Nom<input id="name" value="${safe(p.name)}" placeholder="Prénom ou membre"></label><label>Âge<input id="age" type="number" value="${safe(p.age)}" placeholder="ex : 35"></label><label>Taille cm<input id="height" type="number" value="${safe(p.height)}" placeholder="ex : 175"></label><label>Poids kg<input id="weight" type="number" value="${safe(p.weight)}" placeholder="ex : 80"></label><label>Niveau<select id="lvl"><option value="debutant">Débutant</option><option value="intermediaire">Intermédiaire</option><option value="avance">Avancé</option><option value="expert">Expert</option></select></label><label>Objectif<select id="goal"><option value="remise_forme">Remise en forme</option><option value="perte_poids">Perte de poids</option><option value="prise_masse">Prise de masse</option><option value="performance">Performance</option><option value="bien_etre">Bien-être</option></select></label><label>Programme<select id="program">${programs.map(pr=>`<option value="${pr.id}">${safe(pr.name)} · ${safe(pr.duration)}</option>`).join('')}</select></label><label>Durée<select id="duration"><option value="express">Express 20 min</option><option value="standard">Standard 45 min</option><option value="long">Longue 1h+</option></select></label><label>Lieu<select id="place"><option value="">Choisir</option><option>salle</option><option>domicile</option><option>extérieur</option><option>box crossfit</option></select></label><label>Fatigue 1-5<input id="fatigue" type="number" min="1" max="5" value="${safe(p.fatigue)}" placeholder="1 à 5"></label><label>Sommeil h<input id="sleep" type="number" value="${safe(p.sleep)}" placeholder="ex : 7"></label><label>Stress 1-5<input id="stress" type="number" min="1" max="5" value="${safe(p.stress)}" placeholder="1 à 5"></label></div><button class="btn" onclick="saveCoach()">Enregistrer profil</button><button class="btn secondary" onclick="saveCoach(true)">Enregistrer & générer séance</button></div><div class="card"><h2>Blessures / limitations</h2><div class="grid grid3">${['épaule','coude','poignet','dos','lombaires','hanche','genou','cheville','cardio','nuque'].map(i=>`<label><input class="inj" type="checkbox" value="${i}" ${p.injuries.includes(i)?'checked':''}> ${i}</label>`).join('')}</div></div><div class="card"><h2>Matériel disponible</h2><p class="muted">Rien n’est sélectionné par défaut. Coche uniquement ce que tu as vraiment.</p><div class="grid grid3">${['poids du corps','haltères','barre','banc','machine','poulie','élastique','bâton','corde','rameur','bike','ski erg','extérieur','gants','sac','kettlebell','box','sled','medecine ball','battle rope','barres','barre traction'].map(i=>`<label><input class="eq" type="checkbox" value="${i}" ${p.equipment.includes(i)?'checked':''}> ${i}</label>`).join('')}</div></div>`)}
function saveCoach(go){let p=state.profile;p.name=name.value;p.age=age.value;p.height=height.value;p.weight=weight.value;p.level=lvl.value;p.goal=goal.value;p.place=place.value;p.fatigue=fatigue.value;p.sleep=sleep.value;p.stress=stress.value;p.injuries=[...document.querySelectorAll('.inj:checked')].map(x=>x.value);p.equipment=[...document.querySelectorAll('.eq:checked')].map(x=>x.value);state.program=program.value;state.duration=duration.value;state.profileCreated=!!(p.name&&p.level&&p.goal);if(go){buildSession();state.sessionGenerated=true;setTab('session')}else{save();setTab('home')}}
function exportPDF(){if(!state.sessionGenerated){alert('Génère une séance avant export.');return}let l=level();let rows=session.map((e,i)=>`<tr><td>${i+1}</td><td><b>${safe(e.name)}</b><br>${safe(e.muscles)}</td><td>${l.sets}</td><td>${['cardio_crossfit','mobilite','boxe'].includes(e.category)?l.time:l.reps}</td><td>${l.rest}s</td><td>${safe(e.simple)}</td></tr>`).join('');let html=`<html><head><title>FAFATRAINING PDF</title><style>body{font-family:Arial;padding:28px;color:#111}.head{display:flex;gap:14px;align-items:center}.head img{width:95px;height:95px;border-radius:50%;object-fit:cover}h1{margin:0;font-size:30px}.box{border:1px solid #ddd;border-radius:14px;padding:12px;margin:14px 0}table{width:100%;border-collapse:collapse;font-size:12px}th{background:#050805;color:#62ff69;padding:8px;text-align:left}td{border-bottom:1px solid #ddd;padding:8px;vertical-align:top}.green{color:#169c2a;font-weight:900}</style></head><body><div class="head"><img src="${ASSETS.logo}"><div><div class="green">FAFATRAINING COACHING</div><h1>${safe(currentProgram().name)}</h1><p>Force ton corps · élève ton mental</p></div></div><div class="box">${safe(state.profile.name)} · ${safe(level().label)} · ${safe(goalLabel(state.profile.goal))} · IMC ${bmiText()}</div><table><tr><th>#</th><th>Exercice</th><th>Séries</th><th>Répétitions</th><th>Repos</th><th>Consigne</th></tr>${rows}</table><script>setTimeout(()=>print(),500)<\\/script></body></html>`;let w=window.open('','_blank');w.document.write(html);w.document.close()}
function render(){if(state.tab==='home')app.innerHTML=home();if(state.tab==='coach')app.innerHTML=coach();if(state.tab==='session')app.innerHTML=sessionView();if(state.tab==='library')app.innerHTML=library();if(state.tab==='tracking')app.innerHTML=tracking();setTimeout(()=>{if($('#lvl'))lvl.value=state.profile.level;if($('#goal'))goal.value=state.profile.goal;if($('#place'))place.value=state.profile.place;if($('#program'))program.value=state.program;if($('#duration'))duration.value=state.duration},0)}
document.addEventListener('DOMContentLoaded',boot);if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}))}
