
let exercises=[],programs=[];
let user=JSON.parse(localStorage.getItem('fafatraining_v83'))||{xp:0,level:'debutant',streak:0,completed:0,score:0,program:'musculation',day:0,fatigue:2,history:[],profile:{prenom:'Adhérent',sexe:'homme',age:30,taille:175,poids:78,experience:'debutant',days:3,location:'salle',injuries:[],job:'actif',sleep:7,stress:2,oneRM:{bench:70,squat:90,deadlift:110}},equipment:['poids du corps','haltères','barre','machine','poulie','banc','cardio','kettlebell','box','corde','gants','sac de frappe','élastique']};
Promise.all([fetch('data/exercises.json').then(r=>r.json()),fetch('data/programs.json').then(r=>r.json())]).then(([e,p])=>{exercises=e;programs=p;go('dashboard')});
function save(){localStorage.setItem('fafatraining_v83',JSON.stringify(user))}
function active(r){document.querySelectorAll('[data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===r))}
function bmi(){let h=user.profile.taille/100;return +(user.profile.poids/(h*h)).toFixed(1)}
function corp(){let v=bmi();return v<18.5?'Insuffisance':v<25?'Normale':v<30?'Surpoids':'Obésité'}
function label(l){return{debutant:'Débutant',intermediaire:'Intermédiaire',avance:'Avancé'}[l]||l}
function cp(){return programs.find(p=>p.id===user.program)||programs[0]}function days(){return cp().days.slice(0,Math.max(1,Math.min(user.profile.days,cp().days.length)))}function cd(){let d=days();return d[user.day%d.length]}
function quick(){document.getElementById('quickStats').innerHTML=`<b>${label(user.level)}</b><br>${user.xp} XP · ${user.streak}🔥 · IMC ${bmi()}`}
function go(r){active(r);quick();let v=document.getElementById('view');if(r==='dashboard')dashboard(v);if(r==='programs')programsView(v);if(r==='today')today(v);if(r==='week')week(v);if(r==='library')library(v);if(r==='client')client(v);if(r==='coach')coach(v);if(r==='stats')stats(v)}
function dashboard(v){let d=cd(),p=cp();v.innerHTML=`<div class="layout"><section><section class="hero"><div class="eyebrow">PARCOURS CONSEILLÉ : PROFIL → STYLE → SÉANCE</div><h2>${d.name}</h2><p>${d.subtitle}. Style : ${p.nom}. ${user.profile.days} jours/semaine, niveau ${label(user.level)}, lieu ${user.profile.location}. Tous les calculs changent selon ton profil.</p><span class="pill">🕒 ${d.duration}</span><span class="pill">⚡ ${d.focus}</span><span class="pill">${p.icon} ${p.nom}</span><div class="actions"><button class="btn" onclick="go('today')">▶ COMMENCER</button><button class="btn secondary" onclick="go('programs')">CHANGER DE STYLE</button></div></section><div class="grid grid4" style="margin-top:14px">${programs.map(p=>`<div class="card" onclick="selectProgram('${p.id}')"><h3>${p.icon} ${p.nom}</h3><p class="small">${p.desc}</p><div class="progress"><div style="width:${p.id===user.program?80:25}%"></div></div></div>`).join('')}</div></section><aside><div class="card"><h2>${user.profile.prenom}</h2><p>${label(user.level)} · IMC ${bmi()} (${corp()})</p><p>🔥 ${user.streak} jours<br>✅ ${user.completed} séances<br>🏆 ${user.score} score</p></div><div class="card"><h3>Débutant ?</h3><p class="small">Chaque exercice contient une explication simple, les erreurs à éviter, le niveau et une illustration.</p></div></aside></div>`}
function selectProgram(id){user.program=id;user.day=0;save();go('dashboard')}
function session(){let d=cd();let pool=exercises.filter(e=>d.styles.includes(e.style)&&e.materiel.some(m=>user.equipment.includes(m)));if(d.cats?.length)pool=pool.filter(e=>d.cats.includes(e.categorie)||d.cats.includes(e.style));if(pool.length<d.count)pool=exercises.filter(e=>d.styles.includes(e.style));return pool.slice(0,d.count).map(adapt)}
function adapt(e){let v={...e.variantes[user.level]};if(user.fatigue>=4||user.profile.sleep<6){v.series=Math.max(2,+v.series-1);v.rpe='6';}return{base:e,...v,charge:charge(e,v)}}
function charge(e,v){let pct=parseInt((v.charge_pct||'60').split('–')[0]);let ref=0;if(e.categorie==='pectoraux')ref=user.profile.oneRM.bench;if(e.categorie==='jambes')ref=user.profile.oneRM.squat;if(e.categorie==='chaîne postérieure')ref=user.profile.oneRM.deadlift;if(!ref||e.materiel.includes('poids du corps')||['boxe','trail','cardio','mobilite','hyrox'].includes(e.style))return'RPE '+v.rpe;return Math.round((ref*pct/100)/2.5)*2.5+' kg'}
function today(v){let d=cd(),s=session();v.innerHTML=`<div class="card"><h2>${d.name}</h2><p class="small">${d.subtitle} · ${d.duration} · ${d.focus}</p><span class="pill">${s.length} exercices</span><span class="pill">Charges / repos adaptés</span><span class="pill">Illustrations incluses</span></div>${s.map(card).join('')}<button class="btn" onclick="finish()">SÉANCE TERMINÉE</button>`}
function card(x,i){return`<div class="exercise"><img src="${x.base.image}"><div><span class="pill">#${i+1}</span><h3>${x.nom}</h3><p class="small">${x.base.explication_debutant}</p><b>${x.series} séries · ${x.reps} · repos ${x.repos} · RPE ${x.rpe}</b><div class="tags">${x.base.materiel.slice(0,4).map(t=>`<span>${t}</span>`).join('')}</div></div><div class="load">${x.charge}</div></div>`}
function finish(){let gain=100+session().length*12;user.xp+=gain;user.score+=gain*3;user.completed++;user.streak++;user.day++;user.history.push({date:new Date().toLocaleDateString('fr-FR'),name:cd().name,xp:gain,program:cp().nom});if(user.history.length>30)user.history=user.history.slice(-30);save();go('stats')}
function programsView(v){v.innerHTML=`<div class="card"><h2>Styles d’entraînement</h2><p class="small">Musculation, CrossTraining, Hyrox, Boxe, Trail, Renfo, Cardio, Mobilité.</p></div><div class="grid grid3">${programs.map(p=>`<div class="card" onclick="selectProgram('${p.id}')"><h2>${p.icon} ${p.nom}</h2><p class="small">${p.desc}</p><button class="btn secondary">Choisir</button></div>`).join('')}</div>`}
function week(v){let p=cp();v.innerHTML=`<div class="card"><h2>${p.nom}</h2><p class="small">${user.profile.days} jours/semaine.</p></div><div class="card">${days().map((d,i)=>`<div class="week-row"><div><b>${i+1}. ${d.name}</b><p class="small">${d.subtitle}</p></div><span class="pill">${d.duration}</span></div>`).join('')}</div>`}
function library(v){let groups={};exercises.forEach(e=>{groups[e.styleLabel]=groups[e.styleLabel]||[];groups[e.styleLabel].push(e)});v.innerHTML=`<div class="card"><h2>Bibliothèque Elite</h2><input id="search" placeholder="Recherche : squat, boxe, haltères, trail..." oninput="filterLibrary()"><p class="small">${exercises.length} exercices réels avec explications, variantes, matériel, substitutions et illustrations.</p></div><div>${Object.entries(groups).map(([k,l])=>`<div class="card lib"><h3>${k} · ${l.length}</h3>${l.map(e=>`<span class="pill" data-name="${(e.nom+' '+e.style+' '+e.categorie+' '+e.materiel.join(' ')).toLowerCase()}">${e.icon} ${e.nom}</span>`).join('')}</div>`).join('')}</div>`}
function filterLibrary(){let q=search.value.toLowerCase();document.querySelectorAll('[data-name]').forEach(e=>e.style.display=e.dataset.name.includes(q)?'inline-flex':'none')}
function client(v){let p=user.profile;v.innerHTML=`<div class="card"><h2>Profil adhérent / client</h2><div class="formgrid">${field('prenom','Prénom',p.prenom)}${select('experience','Niveau',['debutant','intermediaire','avance'],p.experience)}${field('days','Jours/semaine',p.days)}${field('age','Âge',p.age)}${field('taille','Taille cm',p.taille)}${field('poids','Poids kg',p.poids)}${select('location','Lieu',['salle','extérieur','studio','domicile'],p.location)}${select('job','Travail',['sédentaire','actif','physique'],p.job)}${field('sleep','Sommeil h',p.sleep)}${field('stress','Stress 1-5',p.stress)}</div><button class="btn" onclick="saveClient()">Enregistrer</button></div><div class="card"><h3>Blessures / limitations</h3><div class="checkgrid">${['épaule','dos','genou','cheville','poignet','hanche'].map(i=>`<label><input class="inj" type="checkbox" value="${i}" ${p.injuries.includes(i)?'checked':''}> ${i}</label>`).join('')}</div></div><div class="card"><h3>Charges repères</h3><div class="formgrid">${field('bench','Bench',p.oneRM.bench)}${field('squat','Squat',p.oneRM.squat)}${field('deadlift','Deadlift',p.oneRM.deadlift)}</div></div>`}
function field(id,l,v){return`<label>${l}<input id="${id}" value="${v}" type="${isNaN(v)?'text':'number'}"></label>`}
function select(id,l,arr,val){return`<label>${l}<select id="${id}">${arr.map(a=>`<option value="${a}" ${a===val?'selected':''}>${a}</option>`).join('')}</select></label>`}
function saveClient(){let p=user.profile;['prenom','experience','location','job'].forEach(k=>p[k]=document.getElementById(k).value);['days','age','taille','poids','sleep','stress'].forEach(k=>p[k]=+document.getElementById(k).value);p.days=Math.max(1,Math.min(6,p.days));p.injuries=[...document.querySelectorAll('.inj:checked')].map(x=>x.value);p.oneRM={bench:+bench.value,squat:+squat.value,deadlift:+deadlift.value};user.level=p.experience;save();go('dashboard')}
function coach(v){let all=['poids du corps','haltères','barre','machine','poulie','banc','barre de traction','cardio','kettlebell','box','corde','gants','sac de frappe','élastique','battle rope','medecine ball','sled','sandbag','skierg','rameur','bike','extérieur','tapis'];v.innerHTML=`<div class="card"><h2>Coach</h2><label>Fatigue ${user.fatigue}/5</label><input id="fatigue" type="range" min="1" max="5" value="${user.fatigue}"><button class="btn" onclick="saveCoach()">Enregistrer</button></div><div class="card"><h3>Matériel disponible</h3><div class="checkgrid">${all.map(m=>`<label><input type="checkbox" class="equip" value="${m}" ${user.equipment.includes(m)?'checked':''}> ${m}</label>`).join('')}</div></div>`}
function saveCoach(){user.fatigue=+fatigue.value;user.equipment=[...document.querySelectorAll('.equip:checked')].map(e=>e.value);if(!user.equipment.length)user.equipment=['poids du corps'];save();go('dashboard')}
function stats(v){let vals=user.history.map(h=>h.xp);if(!vals.length)vals=[0];let max=Math.max(...vals,100);v.innerHTML=`<div class="card"><h2>Suivi</h2><p>${user.xp} XP · ${user.completed} séances · IMC ${bmi()} (${corp()})</p><div class="progress"><div style="width:${Math.min(100,user.xp/150)}%"></div></div></div><div class="card"><h3>Progression</h3><div class="chart">${vals.slice(-12).map(h=>`<div class="bar" style="height:${Math.max(12,h/max*150)}px"></div>`).join('')}</div></div>`}
