
let EXERCISES=[],PROGRAMS=[],CURRENT=null,PAGE='home',STEP=0,LIB='haut_du_corps';
const S={goal:'full',style:'equilibre',level:'auto',duration:'30',place:'choisir',age:'',people:'1',injury:'',fatigue:3,stress:3,equipment:['poids du corps']};
const eqGroups=[
 ['Simple',[['poids du corps','Poids'],['tapis','Tapis'],['mur','Mur'],['chaise','Chaise'],['box','Box']]],
 ['Charges',[['haltères','Haltères'],['barre','Barre'],['kettlebell','KB'],['medecine ball','Med ball'],['sandbag','Sandbag']]],
 ['Salle',[['machine','Machine'],['poulie','Poulie'],['banc','Banc'],['barre traction','Traction'],['presse','Presse']]],
 ['Terrain',[['sac','Sac'],['corde','Corde'],['rameur','Rameur'],['vélo','Vélo'],['extérieur','Extérieur'],['cônes','Cônes']]]
];
const defaultEq={musculation:['haltères','barre','banc'],renfo:['poids du corps','élastique'],full:['poids du corps','haltères'],hiit:['poids du corps'],circuit:['poids du corps','haltères'],boxe:['poids du corps','sac','corde'],crossfit:['poids du corps','haltères','kettlebell','barre'],cross:['poids du corps','extérieur'],hyrox:['rameur','sandbag','haltères'],mobilite:['tapis','mur','poids du corps'],prevention:['tapis','élastique'],explosivite:['extérieur','box','medecine ball']};
const safe=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const logo=()=> 'assets/logo/logo-fafa.jpg';
async function init(){EXERCISES=await fetch('data/exercises.json?v=72').then(r=>r.json());PROGRAMS=await fetch('data/programs.json?v=72').then(r=>r.json());route('home')}
function route(p){PAGE=p;document.body.dataset.page=p;document.body.innerHTML=render(p)+nav()}
function nav(){return `<nav class="tabbar"><button class="${PAGE==='home'?'on':''}" onclick="route('home')">⌂<small>Accueil</small></button><button class="${PAGE==='create'?'on':''}" onclick="STEP=0;route('create')">＋<small>Créer</small></button><button class="${PAGE==='library'?'on':''}" onclick="route('library')">▦<small>Bibliothèque</small></button><button class="${PAGE==='profile'?'on':''}" onclick="route('profile')">◎<small>Profil</small></button></nav>`}
function render(p){return p==='home'?home():p==='create'?create():p==='session'?session():p==='export'?exportMenu():p==='library'?library():p==='profile'?profile():home()}
function back(){return `<button class="back" onclick="route('home')">‹</button>`}
function home(){let h=PremiumEngine.history(), prof=PremiumEngine.profile();return `<main><section class="homeHero"><img class="heroLogo" src="${logo()}" onerror="this.style.display='none'"><div class="heroContent"><p class="kicker">FAFATRAINING PREMIUM</p><h1>Coach terrain.</h1><p class="lead">${prof.name?`Salut ${safe(prof.name)}, crée ta séance adaptée.`:'Une séance claire, rapide, adaptée et exportable.'}</p><button class="primary" onclick="STEP=0;route('create')">Créer une séance</button></div></section><section class="quickCards"><article onclick="STEP=0;route('create')"><b>Créer</b><span>Objectif → style → matériel</span></article><article onclick="route('library')"><b>Bibliothèque</b><span>${EXERCISES.length} mouvements</span></article><article onclick="route('profile')"><b>Profil</b><span>Adaptation athlète</span></article><article><b>Historique</b><span>${h.length} séance(s)</span></article></section></main>`}
function setGoal(g){S.goal=g;S.style=(PremiumEngine.styles[g]||PremiumEngine.styles.full)[0][0];S.equipment=[...(defaultEq[g]||['poids du corps'])];}
function create(){return `<main>${back()}<section class="wizard"><header><h1>Créer une séance</h1><p>${['Choisis l’objectif','Choisis le style','Profil et durée','Matériel','Contraintes'][STEP]}</p></header><div class="progress">${[0,1,2,3,4].map(i=>`<span class="${i<=STEP?'on':''}"></span>`).join('')}</div>${stepContent()}<div class="wizardActions">${STEP>0?`<button class="ghost" onclick="STEP--;route('create')">Retour</button>`:''}${STEP<4?`<button class="primary" onclick="STEP++;route('create')">Continuer</button>`:`<button class="primary" onclick="generate()">Générer</button>`}</div></section></main>`}
function stepContent(){if(STEP===0)return `<div class="choiceGrid">${PROGRAMS.map(p=>`<button class="choice ${S.goal===p.goal?'on':''}" onclick="setGoal('${p.goal}');route('create')"><span>${p.icon}</span><b>${p.name}</b></button>`).join('')}</div>`;if(STEP===1){let st=PremiumEngine.styles[S.goal]||PremiumEngine.styles.full;return `<div class="choiceGrid">${st.map(x=>`<button class="choice ${S.style===x[0]?'on':''}" onclick="S.style='${x[0]}';route('create')"><b>${x[1]}</b><small>${x[2]}</small></button>`).join('')}</div>`}if(STEP===2)return `<div class="form2">${select('level','Niveau',[['auto','Auto profil'],['debutant','Débutant'],['intermediaire','Intermédiaire'],['avance','Avancé'],['expert','Expert']])}${select('duration','Durée',[['20','20 min'],['30','30 min'],['45','45 min'],['60','60 min']])}${select('place','Lieu',[['choisir','Choisir'],['maison','Maison'],['salle','Salle'],['terrain','Terrain'],['exterieur','Extérieur']])}${input('age','Âge séance','11 à 99')}${input('people','Personnes','1')}</div>`;if(STEP===3)return eqGroups.map(g=>`<div class="eqBlock"><h3>${g[0]}</h3><div class="eqGrid">${g[1].map(e=>`<button class="eq ${S.equipment.includes(e[0])?'on':''}" onclick="toggleEq('${e[0]}')">${e[1]}</button>`).join('')}</div></div>`).join('');return `<div class="form2">${select('injury','Zone à protéger',[['','Aucune'],['épaule','Épaule'],['genou','Genou'],['lombaires','Dos/lombaires'],['cheville','Cheville'],['poignet','Poignet'],['cervicales','Cervicales'],['hanches','Hanches']])}<label class="range"><b>Fatigue : ${S.fatigue}</b><input type="range" min="1" max="5" value="${S.fatigue}" oninput="S.fatigue=Number(this.value);route('create')"></label><label class="range"><b>Stress : ${S.stress}</b><input type="range" min="1" max="5" value="${S.stress}" oninput="S.stress=Number(this.value);route('create')"></label></div>`}
function select(k,l,opts){return `<label><b>${l}</b><select onchange="S.${k}=this.value">${opts.map(o=>`<option value="${o[0]}" ${S[k]==o[0]?'selected':''}>${o[1]}</option>`).join('')}</select></label>`}
function input(k,l,ph){return `<label><b>${l}</b><input value="${safe(S[k])}" placeholder="${ph}" oninput="S.${k}=this.value"></label>`}
function toggleEq(v){S.equipment=S.equipment.includes(v)?S.equipment.filter(x=>x!==v):[...S.equipment,v];route('create')}
function generate(){CURRENT=PremiumEngine.generate({...S,equipment:S.equipment},EXERCISES);route('session')}
function session(){if(!CURRENT)return create();return `<main>${back()}<section class="sessionHero"><div><p class="kicker">${safe(CURRENT.title)}</p><h1>${safe(CURRENT.objective)}</h1><p>${safe(CURRENT.adaptation)}</p></div><button class="primary" onclick="route('export')">Menu</button><button class="ghost" onclick="PremiumEngine.saveSession(CURRENT);route('home')">Sauvegarder</button></section><section class="workout">${PremiumEngine.blocks.map(b=>workoutBlock(b)).join('')}</section></main>`}
function workoutBlock(b){let items=CURRENT.blocks[b[0]]||[],info=CURRENT.infos[b[0]]||{};return `<article class="wBlock"><header><span>${b[3]}</span><div><b>${b[1]}</b><small>${b[2]}</small></div></header><div class="wInfo"><b>${info.format}</b><span>${info.structure}</span><span>Repos ${info.rest}</span></div>${items.map((e,i)=>`<div class="exercise"><b>${i+1}. ${safe(e.displayName)}</b><span>${safe(e.prescription)}</span><small>${safe(e.instruction)}</small></div>`).join('')}</article>`}
function exportMenu(){if(!CURRENT)return create();return `<main>${back()}<section id="menuCard" class="menuClean"><header><img src="${logo()}" onerror="this.style.display='none'"><div><p>MENU SÉANCE</p><h1>${safe(CURRENT.title)}</h1><span>${safe(CURRENT.meta.duration)} min · ${safe(CURRENT.meta.level)} · ${safe(CURRENT.meta.equipment.join ? CURRENT.meta.equipment.join(', ') : CURRENT.meta.equipment)}</span></div></header><section class="goalBox"><b>Objectif</b><span>${safe(CURRENT.objective)}</span></section><section class="badgeRow">${CURRENT.badges.map(x=>`<b>${safe(x)}</b>`).join('')}</section>${PremiumEngine.blocks.map(menuBlock).join('')}<footer>FAFATRAINING · FORGE TON CORPS</footer></section><div class="actions"><button class="primary" onclick="saveSvg()">Enregistrer image</button><button class="ghost" onclick="window.print()">PDF</button></div></main>`}
function menuBlock(b){let items=CURRENT.blocks[b[0]]||[],info=CURRENT.infos[b[0]]||{};return `<section class="mClean"><header><h2>${b[1]}</h2><p>${info.format} · ${info.structure}</p></header>${items.map((e,i)=>`<div><b>${i+1}. ${safe(e.displayName)}</b><span>${safe(e.prescription)}</span><small>${safe(e.instruction)}</small></div>`).join('')}</section>`}
function library(){let cats=[['haut_du_corps','Haut'],['bas_du_corps','Bas'],['core','Core'],['cardio','Cardio'],['boxe','Boxe'],['mobilite','Mobilité'],['reeducation','Prévention']];let list=EXERCISES.filter(e=>e.group===LIB);return `<main>${back()}<section class="library"><h1>Bibliothèque</h1><p>${EXERCISES.length} mouvements classés.</p><div class="tabs">${cats.map(c=>`<button class="${LIB===c[0]?'on':''}" onclick="LIB='${c[0]}';route('library')">${c[1]}</button>`).join('')}</div><input class="search" placeholder="Rechercher..." oninput="filterLib(this.value)"><div id="libList" class="libGrid">${libCards(list)}</div></section></main>`}
function libCards(list){return list.map(e=>`<article><b>${safe(e.name)}</b><span>${safe(e.pattern)} · ${safe((e.muscles||[]).join(' / '))}</span><p>${safe(e.human_explain)}</p><small>${safe(e.coach_note)}</small></article>`).join('')}
function filterLib(q){q=q.toLowerCase();document.getElementById('libList').innerHTML=libCards(EXERCISES.filter(e=>e.group===LIB&&(e.name.toLowerCase().includes(q)||e.pattern.toLowerCase().includes(q)||(e.muscles||[]).join(' ').toLowerCase().includes(q))))}
function profile(){let p=PremiumEngine.profile();return `<main>${back()}<section class="profile"><h1>Profil athlète</h1><div class="form2">${pfield('name','Nom',p.name||'')}${pfield('age','Âge',p.age||'')}${pfield('goal','Objectif',p.goal||'forme')}${pfield('sport','Sport',p.sport||'general')}</div><button class="primary full" onclick="saveProfile()">Sauvegarder</button></section></main>`}
function pfield(k,l,v){return `<label><b>${l}</b><input id="pf_${k}" value="${safe(v)}"></label>`}
function saveProfile(){let p={};['name','age','goal','sport'].forEach(k=>p[k]=document.getElementById('pf_'+k).value);PremiumEngine.saveProfile(p);route('home')}
function saveSvg(){let n=document.getElementById('menuCard'),svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${n.offsetWidth}" height="${n.offsetHeight}"><foreignObject width="100%" height="100%">${new XMLSerializer().serializeToString(n)}</foreignObject></svg>`,blob=new Blob([svg],{type:'image/svg+xml'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='FAFATRAINING-menu.svg';a.click()}
init();
